# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  # Run commander scrape weekly on Saturday at 8am in development
  weekly_commander_scrape:
    class: ScrapeEdhrecCommandersJob
    queue: default
    schedule: every saturday at 8am
    args: []

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  daily_card_price_update:
    class: UpdateCardPricesJob
    queue: default
    schedule: every day at 7am
    args: []

  weekly_commander_scrape:
    class: ScrapeEdhrecCommandersJob
    queue: default
    schedule: every sunday at 8am
    args: []
