services:
  db:
    image: postgres:16-alpine
    container_name: mtg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    container_name: mtg_backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      EDITOR: nano
      RUBY_VERSION: ${RUBY_VERSION}
      BUNDLE_PATH: /bundle
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_HOST: db
      DB_USER: ${POSTGRES_USER_NAME}
      DB_PASS: ${POSTGRES_USER_PASSWORD}
      DB_NAME: ${POSTGRES_DB_NAME}
      DATABASE_URL: ${POSTGRES_DB_URL}
    volumes:
      - ./backend:/backend  # Rails code
      - bundle_cache:/bundle       # Gems
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: mtg_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:3000
    # Remove volumes: and command: in production since it will use the built-app
    # and does not require hot reload
    volumes:
      - ./frontend:/frontend  # Vite hot reload
      - frontend_node_modules:/frontend/node_modules

volumes:
  postgres_data:
  bundle_cache:
  frontend_node_modules:
